port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info

proxies:
  - name: "Trojan-AWS"
    type: trojan
    server: 44.245.159.5
    port: 443
    password: "bSh896F4hIb+Wwi23aWjF784cCiUJxiRaYMN95zO59s="
    sni: 44.245.159.5
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - Trojan-AWS-mo
      - DIRECT

rules:
  # Telegram 走代理
  - DOMAIN-SUFFIX,telegram.org,Proxy
  - DOMAIN-SUFFIX,t.me,Proxy

  # 常见国外域名走代理（避免误判）
  - DOMAIN-SUFFIX,google.com,Proxy
  - DOMAIN-SUFFIX,facebook.com,Proxy
  - DOMAIN-SUFFIX,twitter.com,Proxy
  - DOMAIN-SUFFIX,x.com,Proxy

  # 国内直连
  - GEOIP,CN,DIRECT

  # 其他全部走代理
  - MATCH,Proxy
